name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt
      - name: Lint
        run: |
          black --check src tests
          isort --check-only src tests
          flake8 src tests
          mypy src
          ruff check src tests
      - name: Test
        run: |
          pytest -q
